In [4]:
import pandas as pd
import pyarrow.parquet as pq

In [1]:
path = "../data/bts_2022_2026_combined.parquet"

In [5]:
pf = pq.ParquetFile(path)
first_batch = next(pf.iter_batches(batch_size=100_000))
df = first_batch.to_pandas()

In [6]:
df.head()

,DepDel15,FlightDate,Year,Reporting_Airline,Quarter,Month,DayofMonth,DayOfWeek,Origin,Dest,...,DepartureDelayGroups,TaxiOut,WheelsOff,ArrDelay,ArrDel15,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0.0,2022-01-14,2022,YX,1,1,14,5,CMH,DCA,...,-1.0,28.0,1249.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN
1,0.0,2022-01-15,2022,YX,1,1,15,6,CMH,DCA,...,-1.0,19.0,1233.0,-24.0,0.0,NaN,NaN,NaN,NaN,NaN
2,0.0,2022-01-16,2022,YX,1,1,16,7,CMH,DCA,...,-1.0,16.0,1234.0,-13.0,0.0,NaN,NaN,NaN,NaN,NaN
3,0.0,2022-01-17,2022,YX,1,1,17,1,CMH,DCA,...,-1.0,32.0,1249.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN
4,0.0,2022-01-18,2022,YX,1,1,18,2,CMH,DCA,...,-1.0,11.0,1229.0,-29.0,0.0,NaN,NaN,NaN,NaN,NaN

In [7]:
df.columns

Index(['DepDel15', 'FlightDate', 'Year', 'Reporting_Airline', 'Quarter',
       'Month', 'DayofMonth', 'DayOfWeek', 'Origin', 'Dest', 'OriginState',
       'DestState', 'CRSDepTime', 'DepTimeBlk', 'CRSArrTime', 'CRSElapsedTime',
       'Distance', 'Flight_Number_Reporting_Airline', 'Tail_Number',
       'Cancelled', 'CancellationCode', 'Diverted', 'DepTime', 'DepDelay',
       'DepDelayMinutes', 'DepartureDelayGroups', 'TaxiOut', 'WheelsOff',
       'ArrDelay', 'ArrDel15', 'CarrierDelay', 'WeatherDelay', 'NASDelay',
       'SecurityDelay', 'LateAircraftDelay'],
      dtype='str')

In [8]:
df.describe()

,DepDel15,Year,Quarter,Month,DayofMonth,DayOfWeek,CRSDepTime,CRSArrTime,CRSElapsedTime,Distance,...,DepartureDelayGroups,TaxiOut,WheelsOff,ArrDelay,ArrDel15,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,93459.000000,100000.0,100000.0,100000.0,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,...,93459.000000,93447.000000,93447.000000,93113.000000,93113.000000,18427.000000,18427.000000,18427.000000,18427.000000,18427.000000
mean,0.202410,2022.0,1.0,1.0,16.506150,3.956940,1314.071300,1488.57782,141.140320,752.225600,...,0.197477,19.141428,1350.672863,5.805698,0.197899,45.509578,7.878059,5.293157,0.070983,19.318609
std,0.401798,0.0,0.0,0.0,8.978255,2.047293,468.584612,491.93851,69.807426,575.736603,...,2.510513,10.812456,478.280381,59.372026,0.398418,90.262698,42.250763,21.177938,4.635101,56.664274
min,0.000000,2022.0,1.0,1.0,1.000000,1.000000,10.000000,1.00000,5.000000,66.000000,...,-2.000000,2.000000,1.000000,-73.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2022.0,1.0,1.0,8.000000,2.000000,920.000000,1122.00000,92.000000,360.000000,...,-1.000000,13.000000,950.000000,-18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,2022.0,1.0,1.0,17.000000,4.000000,1315.000000,1512.00000,123.000000,594.000000,...,-1.000000,16.000000,1338.000000,-8.000000,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,2022.0,1.0,1.0,24.000000,6.000000,1715.000000,1855.00000,170.000000,967.000000,...,0.000000,22.000000,1739.000000,7.000000,0.000000,50.000000,0.000000,0.000000,0.000000,8.000000
max,1.000000,2022.0,1.0,1.0,31.000000,7.000000,2359.000000,2359.00000,675.000000,4962.000000,...,12.000000,193.000000,2400.000000,1716.000000,1.000000,1716.000000,1191.000000,706.000000,608.000000,1607.000000

In [9]:
print(pf.schema_arrow.names)

['DepDel15', 'FlightDate', 'Year', 'Reporting_Airline', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'Origin', 'Dest', 'OriginState', 'DestState', 'CRSDepTime', 'DepTimeBlk', 'CRSArrTime', 'CRSElapsedTime', 'Distance', 'Flight_Number_Reporting_Airline', 'Tail_Number', 'Cancelled', 'CancellationCode', 'Diverted', 'DepTime', 'DepDelay', 'DepDelayMinutes', 'DepartureDelayGroups', 'TaxiOut', 'WheelsOff', 'ArrDelay', 'ArrDel15', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']